/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.eldelbit.conectoresdesktop;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import es.eldelbit.conectoresdesktop.db.DB;
import es.eldelbit.conectoresdesktop.models.Cliente;
import es.eldelbit.conectoresdesktop.respositories.ClienteRepository;
import jakarta.persistence.EntityManager;

/**
 *
 * @author virtualbox
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTA = new javax.swing.JTextArea();
        jClear = new javax.swing.JButton();
        jBMostrar = new javax.swing.JButton();
        jTF = new javax.swing.JTextField();
        jTFSleep = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFRepeticiones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBListar.setText("LISTAR");
        jBListar.setName(""); // NOI18N
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });

        jTA.setEditable(false);
        jTA.setColumns(20);
        jTA.setRows(5);
        jScrollPane2.setViewportView(jTA);

        jClear.setText("LIMPIAR");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jBMostrar.setText("MOSTRAR");
        jBMostrar.setName(""); // NOI18N
        jBMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarActionPerformed(evt);
            }
        });

        jTF.setText("1");

        jTFSleep.setText("100");

        jLabel1.setText("Sleep (ms)");

        jLabel2.setText("ID");

        jLabel3.setText("Repeticiones");

        jTFRepeticiones.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFSleep, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTFRepeticiones, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jBListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jClear))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed

        int rep;
        try {
            rep = Integer.parseInt(jTFRepeticiones.getText());
        } catch (Exception ex) {
            jTA.insert("LISTAR. ERROR: " + ex.getMessage() + "\n", 0);
            return;
        }

        for (int x = 0; x < rep; x++) {

            int j, s;
            String pre;
            try {
                j = ++i;
                s = Integer.parseInt(jTFSleep.getText());
                pre = String.format("%03d. LISTAR. ", j);
            } catch (Exception ex) {
                jTA.insert("LISTAR. ERROR: " + ex.getMessage() + "\n", 0);
                return;
            }

            new Thread("" + j) {
                @Override
                public void run() {
                    jTA.insert(pre + "Inicio\n", 0);

                    EntityManager em = null;

                    try {

                        em = DB.createEntityManager();

                        var clientes = ClienteRepository.get(em);

                        for (Cliente cliente : clientes) {
                            jTA.insert(pre + "Cliente: " + getGson().toJson(cliente) + "\n", 0);

                            if (s > 0) {
                                Thread.sleep(s);
                            }
                        }

                    } catch (Exception ex) {
                        jTA.insert(pre + "ERROR: " + ex.getMessage() + "\n", 0);
                    } finally {
                        DB.closeEntityManager(em);
                    }

                    jTA.insert(pre + "Fin.\n", 0);
                }
            }.start();
        }

    }//GEN-LAST:event_jBListarActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        jTA.setText("");
    }//GEN-LAST:event_jClearActionPerformed

    private void jBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarActionPerformed

        int rep;
        try {
            rep = Integer.parseInt(jTFRepeticiones.getText());
        } catch (Exception ex) {
            jTA.insert("ERROR. MOSTRAR: " + ex.getMessage() + "\n", 0);
            return;
        }

        for (int x = 0; x < rep; x++) {

            int j, s;
            long id;
            String pre;
            try {
                j = ++i;
                s = Integer.parseInt(jTFSleep.getText());
                id = Long.parseLong(jTF.getText());
                pre = String.format("%03d. MOSTRAR (%d). ", j, id);
            } catch (Exception ex) {
                jTA.insert("ERROR. MOSTRAR: " + ex.getMessage() + "\n", 0);
                return;
            }

            new Thread("" + j) {
                @Override
                public void run() {
                    jTA.insert(pre + "Inicio\n", 0);

                    EntityManager em = null;

                    try {

                        em = DB.createEntityManager();

                        var cliente = ClienteRepository.find(em, id);

                        jTA.insert(pre + "Cliente: " + getGson().toJson(cliente) + "\n", 0);

                        if (s > 0) {
                            Thread.sleep(s);
                        }

                    } catch (Exception ex) {
                        jTA.insert(pre + "ERROR: " + ex.getMessage() + "\n", 0);
                    } finally {
                        DB.closeEntityManager(em);
                    }

                    jTA.insert(pre + "Fin.\n", 0);
                }
            }.start();
        }

    }//GEN-LAST:event_jBMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    private Gson getGson() {
        return new GsonBuilder()
                .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'")
                // .setPrettyPrinting()
                .create();
    }

    private int i = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBListar;
    private javax.swing.JButton jBMostrar;
    private javax.swing.JButton jClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTA;
    private javax.swing.JTextField jTF;
    private javax.swing.JTextField jTFRepeticiones;
    private javax.swing.JTextField jTFSleep;
    // End of variables declaration//GEN-END:variables
}
